### ISSUE TITLE
Account name in pattern wrong when using --account switch

### ISSUE THREAD

**Issue by BernhardBln** [leflamm/afpre#28]
When using `PATTERN="${ACCOUNT}|${ROLE}"` in the config file, and overwriting the account using `--account=...` on the command line, the PATTERN displays the account which was defined in the config file (and not the overwritten one from the command line).

**Comment by leflamm** [comment]
Plz check latest commit. Thx!

**Comment by BernhardBln** [comment]
It works! :)
