### ISSUE TITLE
Date returned null?

### ISSUE THREAD

**Issue by uweschaefer** [leflamm/afpre#3]
Ubuntu 16.04:

afpre x y
** checking dependecies
** reading credentials
username: z
password: 
** authenticating as z for x/y against myafphost
** assembling environment
date: invalid date ‘null’
** starting bash

**Comment by leflamm** [comment]
Thx. Looking into it.

**Comment by leflamm** [comment]
Can you plz try to reproduce this using the latest version?

**Comment by uweschaefer** [comment]
no longer observable, thx.
