### ISSUE TITLE
Not possible to exit afpre when hanging on token renewal

### ISSUE THREAD

**Issue by BernhardBln** [leflamm/afpre#38]
When afpre hangs while renewing the token ("token expired - need to renew..."), it is not possible to exit afpre using `ctrl + c`:

```
token expired - need to renew...
authenticating as ... for ... against ...
^C
token expired - need to renew...
authenticating as ... for ... against ...
^C
token expired - need to renew...
authenticating as ... for ... against ...
```

Instead, it just tries again to renew the token.

**Comment by leflamm** [comment]
Plz try https://github.com/leflamm/afpre/releases/tag/0.9.18

**Comment by BernhardBln** [comment]
Works, thanks :)
